In [51]:
%matplotlib notebook

In [52]:
# Dependencies
import numpy as np 
import pandas as pd
pd.set_option('display.max_rows', 30000)
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [53]:
# Compare Low Crime and High Crime Income Levels
incomelowcrime="Low Crime/Data/incomecrime.csv"
incomelowcrime=pd.read_csv(incomelowcrime)
incomehighcrime="High Crime/Data/incomecrime.csv"
incomehighcrime=pd.read_csv(incomehighcrime)

# Merge the Low Crime data with the High Crime data
incomemerge=pd.merge(left=incomelowcrime,right=incomehighcrime,on='State',suffixes=('_Low Crime','_High Crime'))
income_mean = round(incomemerge[["Median Income_Low Crime","Median Income_High Crime"]].mean(),2)
income_median = round(incomemerge[["Median Income_Low Crime","Median Income_High Crime"]].median(),2)
income_deviation = round(incomemerge[["Median Income_Low Crime","Median Income_High Crime"]].std(),2)
income_max=round(incomemerge[["Median Income_Low Crime","Median Income_High Crime"]].max(),2)
income_min=round(incomemerge[["Median Income_Low Crime","Median Income_High Crime"]].min(),2)
income_summary_table = pd.DataFrame({"Mean":income_mean, "Median":income_median, 
                                     "Standard Deviation":income_deviation, "Max":income_max, "Min":income_min})
income_summary_table

,Mean,Median,Standard Deviation,Max,Min
Median Income_Low Crime,32264.06,29703.0,11451.93,60007.0,17338.0
Median Income_High Crime,21892.53,19231.0,6588.56,35718.0,12750.0

In [54]:
# Compare Low Crime and High Crime Unemployment Levels
unemploymentlowcrime="Low Crime/Data/unemploymentcrime.csv"
unemploymentlowcrime=pd.read_csv(unemploymentlowcrime)
unemploymenthighcrime="High Crime/Data/unemploymentcrime.csv"
unemploymenthighcrime=pd.read_csv(unemploymenthighcrime)

# Merge the Low Crime data with the High Crime data
unemploymentmerge=pd.merge(left=unemploymentlowcrime,right=unemploymenthighcrime,on='State',
                           suffixes=('_Low Crime','_High Crime'))
unemployment_mean = round(unemploymentmerge[["% Unemployment_Low Crime","% Unemployment_High Crime"]].mean(),2)
unemployment_median = round(unemploymentmerge[["% Unemployment_Low Crime","% Unemployment_High Crime"]].median(),2)
unemployment_deviation = round(unemploymentmerge[["% Unemployment_Low Crime","% Unemployment_High Crime"]].std(),2)
unemployment_max=round(unemploymentmerge[["% Unemployment_Low Crime","% Unemployment_High Crime"]].max(),2)
unemployment_min=round(unemploymentmerge[["% Unemployment_Low Crime","% Unemployment_High Crime"]].min(),2)
unemployment_summary_table = pd.DataFrame({"Mean":unemployment_mean, "Median":unemployment_median, 
                                     "Standard Deviation":unemployment_deviation, 
                                     "Max":unemployment_max, "Min":unemployment_min})
unemployment_summary_table

                           Mean  Median  Standard Deviation   Max   Min
% Unemployment_Low Crime   3.69    3.72                1.43   7.2  1.64
% Unemployment_High Crime  7.18    7.05                3.41  15.3  0.42

In [55]:
# Compare Low Crime and High Crime Population Levels
populationlowcrime="Low Crime/Data/totalpopulation.csv"
populationlowcrime=pd.read_csv(populationlowcrime)
populationhighcrime="High Crime/Data/totalpopulation.csv"
populationhighcrime=pd.read_csv(populationhighcrime)

# Merge the Low Crime data with the High Crime data
populationmerge=pd.merge(left=populationlowcrime,right=populationhighcrime,on='State',
                           suffixes=('_Low Crime','_High Crime'))
population_mean = round(populationmerge[["Population_Low Crime","Population_High Crime"]].mean(),2)
population_median = round(populationmerge[["Population_Low Crime","Population_High Crime"]].median(),2)
population_deviation = round(populationmerge[["Population_Low Crime","Population_High Crime"]].std(),2)
population_max=round(populationmerge[["Population_Low Crime","Population_High Crime"]].max(),2)
population_min=round(populationmerge[["Population_Low Crime","Population_High Crime"]].min(),2)
population_summary_table = pd.DataFrame({"Mean":population_mean, "Median":population_median, 
                                     "Standard Deviation":population_deviation, 
                                     "Max":population_max, "Min":population_min})
population_summary_table

                           Mean  Median  Standard Deviation       Max    Min
Population_Low Crime   10690.65  5501.5            11802.15   57165.0  630.0
Population_High Crime  49831.20  7144.0           143891.96  622454.0   60.0

In [56]:
# Compare Low Crime and High Crime Marital Status
# Read High Crime Marital Status csv into a new dataframe
maritallowcrime_df = pd.read_csv('Low Crime/Data/maritalstatuscrime.csv')
maritalhighcrime_df = pd.read_csv('High Crime/Data/maritalstatuscrime.csv')

# Summarize the Low Crime Data
lc_never_married = round(maritallowcrime_df["% Never Married"].mean(),2)
lc_married = round(maritallowcrime_df["% Married"].mean(),2)
lc_divorced = round(maritallowcrime_df["% Divorced"].mean(),2)
lc_separated = round(maritallowcrime_df["% Separated"].mean(),2)
lc_widowed = round(maritallowcrime_df["% Widowed"].mean(),2)

# Summarize the High Crime Data
hc_never_married = round(maritalhighcrime_df["% Never Married"].mean(),2)
hc_married = round(maritalhighcrime_df["% Married"].mean(),2)
hc_divorced = round(maritalhighcrime_df["% Divorced"].mean(),2)
hc_separated = round(maritalhighcrime_df["% Separated"].mean(),2)
hc_widowed = round(maritalhighcrime_df["% Widowed"].mean(),2)

maritalmerge = {'Low/High': ['Low Crime Locations','High Crime Locations'],
                '% Never Married': [lc_never_married, hc_never_married],
                '% Married': [lc_married, hc_married],
                '% Divorced': [lc_divorced, hc_divorced],
                '% Separated': [lc_separated, hc_separated],
                '% Widowed': [lc_widowed, hc_widowed]}

maritalmerge_df = pd.DataFrame(maritalmerge)
maritalmerge_df

,Low/High,% Never Married,% Married,% Divorced,% Separated,% Widowed
0,Low Crime Locations,26.10,53.59,11.95,2.01,6.35
1,High Crime Locations,38.32,37.27,13.36,3.24,7.82

In [57]:
# Compare Low Crime and High Crime Education Level
# Read High Crime Education Leval csv into a new dataframe
educationlowcrime_df = pd.read_csv('Low Crime/Data/educationcrime.csv')
educationhighcrime_df = pd.read_csv('High Crime/Data/educationcrime.csv')

# Summarize the Low Crime Data
lc_none = round(educationlowcrime_df["% None"].mean(),2)
lc_highschool = round(educationlowcrime_df["% High School"].mean(),2)
lc_assocaites = round(educationlowcrime_df["% Associates"].mean(),2)
lc_bachelors = round(educationlowcrime_df["% Bachelors"].mean(),2)
lc_graduate = round(educationlowcrime_df["% Graduate"].mean(),2)

# Summarize the High Crime Data
hc_none = round(educationhighcrime_df["% None"].mean(),2)
hc_highschool = round(educationhighcrime_df["% High School"].mean(),2)
hc_assocaites = round(educationhighcrime_df["% Associates"].mean(),2)
hc_bachelors = round(educationhighcrime_df["% Bachelors"].mean(),2)
hc_graduate = round(educationhighcrime_df["% Graduate"].mean(),2)

educationmerge = {'Low/High': ['Low Crime Locations','High Crime Locations'],
                '% None': [lc_none, hc_none],
                '% High School': [lc_highschool, hc_highschool],
                '% Associates': [lc_assocaites, hc_assocaites],
                '% Bachelor': [lc_bachelors, hc_bachelors],
                '% Graduate': [lc_graduate, hc_graduate]}

educationmerge_df = pd.DataFrame(educationmerge)
educationmerge_df

,Low/High,% None,% High School,% Associates,% Bachelor,% Graduate
0,Low Crime Locations,9.64,26.43,29.02,21.81,13.10
1,High Crime Locations,18.91,34.05,29.46,11.59,5.99

In [62]:
# Compare Low Crime and High Crime Race
# Read High Crime Race csv into a new dataframe
racelowcrime_df = pd.read_csv('Low Crime/Data/racecrime.csv')
racehighcrime_df = pd.read_csv('High Crime/Data/racecrime.csv')

# Summarize the Low Crime Data
lc_black = round(racelowcrime_df["% Black"].mean(),2)
lc_asian = round(racelowcrime_df["% Asian"].mean(),2)
lc_pacific = round(racelowcrime_df["% Native Hawaiian/Pacific Islander"].mean(),2)
lc_white = round(racelowcrime_df["% White"].mean(),2)
lc_latino = round(racelowcrime_df["% Hispanic/Latino"].mean(),2)
lc_native = round(racelowcrime_df["% American Indian/Alaskan Native"].mean(),2)
lc_two = round(racelowcrime_df["% Two or More"].mean(),2)
lc_other = round(racelowcrime_df["% Other"].mean(),2)

# Summarize the High Crime Data
hc_black = round(racehighcrime_df["% Black"].mean(),2)
hc_asian = round(racehighcrime_df["% Asian"].mean(),2)
hc_pacific = round(racehighcrime_df["% Native Hawaiian/Pacific Islander"].mean(),2)
hc_white = round(racehighcrime_df["% White"].mean(),2)
hc_latino = round(racehighcrime_df["% Hispanic/Latino"].mean(),2)
hc_native = round(racehighcrime_df["% American Indian/Alaskan Native"].mean(),2)
hc_two = round(racehighcrime_df["% Two or More"].mean(),2)
hc_other = round(racehighcrime_df["% Other"].mean(),2)

racemerge = {'Low/High': ['Low Crime Locations','High Crime Locations'],
                '% Black': [lc_black, hc_black],
                '% Asian': [lc_asian, hc_asian],
                '% Native Hawaiian/Pacific Islander': [lc_pacific, hc_pacific],
                '% White': [lc_white, hc_white],
                '% Hispanic/Latin': [lc_latino, hc_latino],
                '% American Indian/Alaskan Native': [lc_native, hc_native],
                '% Two or More': [lc_two, hc_two],
                '% Other': [lc_other, hc_other]}

racemerge_df = pd.DataFrame(racemerge)
racemerge_df

,Low/High,% Black,% Asian,% Native Hawaiian/Pacific Islander,% White,% Hispanic/Latin,% American Indian/Alaskan Native,% Two or More,% Other
0,Low Crime Locations,3.61,2.45,0.04,79.03,7.64,3.52,2.41,1.30
1,High Crime Locations,27.26,1.63,0.14,46.52,13.67,3.86,3.45,3.48

In [59]:
# Compare Low Crime and High Crime School Enrollment
# Read High Crime School Enrollment csv into a new dataframe
schoollowcrime_df = pd.read_csv('Low Crime/Data/schoolenrollmentcrime.csv')
schoolhighcrime_df = pd.read_csv('High Crime/Data/schoolenrollmentcrime.csv')

# Summarize the Low Crime Data
lc_nursery = round(schoollowcrime_df["% Nursery-Pre-School"].mean(),2)
lc_kindergarten = round(schoollowcrime_df["% Kindergarten"].mean(),2)
lc_elementary = round(schoollowcrime_df["% 1st-4th"].mean(),2)
lc_middle = round(schoollowcrime_df["% 5th-8th"].mean(),2)
lc_high = round(schoollowcrime_df["% 9th-12th"].mean(),2)

# Summarize the High Crime Data
hc_nursery = round(schoolhighcrime_df["% Nursery-Pre-School"].mean(),2)
hc_kindergarten = round(schoolhighcrime_df["% Kindergarten"].mean(),2)
hc_elementary = round(schoolhighcrime_df["% 1st-4th"].mean(),2)
hc_middle = round(schoolhighcrime_df["% 5th-8th"].mean(),2)
hc_high = round(schoolhighcrime_df["% 9th-12th"].mean(),2)

schoolmerge = {'Low/High': ['Low Crime Locations','High Crime Locations'],
                '% Nursery-Pre-School': [lc_nursery, hc_nursery],
                '% Kindergarten': [lc_kindergarten, hc_kindergarten],
                '% 1st-4th': [lc_elementary, hc_elementary],
                '% 5th-8th': [lc_middle, hc_middle],
                '% 9th-12th': [lc_high, hc_high]}

schoolmerge_df = pd.DataFrame(schoolmerge)
schoolmerge_df

,Low/High,% Nursery-Pre-School,% Kindergarten,% 1st-4th,% 5th-8th,% 9th-12th
0,Low Crime Locations,7.07,6.82,27.43,30.99,27.70
1,High Crime Locations,8.91,7.47,29.77,26.53,27.32